//
//  Constants.swift
//  Pokemon-DataBase
//
//  Created by Yi-Yun Chen on 2017/11/19.
//  Copyright © 2017年 Yi-Yun Chen. All rights reserved.
//

import Foundation

var POKEMONS = [
    Pokemon(index: 1, name: "妙蛙種子", evolution: "LV16時進化成妙蛙草", types: [.Grass, .Poison], movement: [Movement(level: 1, name: "撞擊"),Movement(level: 3, name: "叫聲"),Movement(level: 7, name: "藤鞭"),Movement(level: 13, name: "毒粉"),Movement(level: 13, name: "催眠粉"),Movement(level: 15, name: "猛撞")]),
    Pokemon(index: 2, name: "妙蛙草", evolution: "LV32時進化成妙蛙花", types: [.Grass, .Poison], movement: [Movement(level: 20, name: "飛葉快刀"),Movement(level: 23, name: "甜甜香氣"),Movement(level: 28, name: "生長"),Movement(level: 31, name: "捨身衝撞")]),
    Pokemon(index: 3, name: "妙蛙花", evolution: "-----", types: [.Grass, .Poison], movement: [Movement(level: 39, name: "煩惱種子"),Movement(level: 45, name: "光合作用"),Movement(level: 50, name: "落英繽紛"),Movement(level: 53, name: "日光束")]),
    Pokemon(index: 4, name: "小火龍", evolution: "LV16時進化成火恐龍", types: [.Fire], movement: [Movement(level: 1, name: "抓"),Movement(level: 1, name: "叫聲"),Movement(level: 7, name: "火花"),Movement(level: 10, name: "煙幕")]),
    Pokemon(index: 5, name: "火恐龍", evolution: "LV36時進化成噴火龍", types: [.Fire], movement: [Movement(level: 17, name: "龍之怒"),Movement(level: 21, name: "鬼面"),Movement(level: 28, name: "火焰牙"),Movement(level: 32, name: "烈焰濺射")]),
    Pokemon(index: 6, name: "噴火龍", evolution: "-----", types: [.Fire, .Fly], movement: [Movement(level: 41, name: "劈開"),Movement(level: 47, name: "噴射火焰"),Movement(level: 56, name: "火焰漩渦"),Movement(level: 62, name: "煉獄"),Movement(level: 71, name: "熱風"),Movement(level: 77, name: "閃焰衝鋒")]),
    Pokemon(index: 7, name: "傑尼龜", evolution: "LV16時進化成卡咪龜", types: [.Water], movement: [Movement(level: 1, name: "撞擊"),Movement(level: 4, name: "搖尾巴"),Movement(level: 7, name: "水槍"),Movement(level: 13, name: "泡沫")]),
    Pokemon(index: 8, name: "卡咪龜", evolution: "LV36時進化成水箭龜", types: [.Water], movement: [Movement(level: 17, name: "咬住"),Movement(level: 21, name: "高速流轉"),Movement(level: 25, name: "守住"),Movement(level: 29, name: "水之波動"),Movement(level: 33, name: "水流尾")]),
    Pokemon(index: 9, name: "水箭龜", evolution: "-----", types: [.Water], movement: [Movement(level: 40, name: "火箭頭錘"),Movement(level: 47, name: "鐵壁"),Movement(level: 54, name: "求雨"),Movement(level: 60, name: "水炮")]),
    Pokemon(index: 10, name: "綠毛蟲", evolution: "LV7時進化成鐵甲蛹", types: [.Insect], movement: [Movement(level: 1, name: "撞擊"),Movement(level: 1, name: "吐絲")]),
    Pokemon(index: 11, name: "鐵甲蛹", evolution: "LV10時進化成巴大蝴", types: [.Insect], movement: [Movement(level: 7, name: "變硬")]),
    Pokemon(index: 12, name: "巴大蝴", evolution: "-----", types: [.Insect, .Fly], movement: [Movement(level: 10, name: "起風"),Movement(level: 11, name: "念力"),Movement(level: 13, name: "毒粉"),Movement(level: 13, name: "麻痺粉"), Movement(level: 13, name: "催眠粉"),Movement(level: 17, name: "幻象光線"),Movement(level: 19, name: "銀色旋風"),Movement(level: 23, name: "超音波"),Movement(level: 25, name: "神秘守護"),Movement(level: 29, name: "吹飛"),Movement(level: 31, name: "蟲鳴"),Movement(level: 35, name: "憤怒粉"),Movement(level: 37, name: "誘惑"),Movement(level: 41, name: "順風"),Movement(level: 43, name: "空氣斬"),Movement(level: 47, name: "蝶舞")]),
    Pokemon(index: 13, name: "獨角蟲", evolution: "LV7時進化成鐵殼昆", types: [.Insect, .Poison], movement: [Movement(level: 1, name: "毒針"),Movement(level: 1, name: "吐絲")]),
    Pokemon(index: 14, name: "鐵殼昆", evolution: "LV10時進化成大針蜂", types: [.Insect, .Poison], movement: [Movement(level: 7, name: "變硬")]),
    Pokemon(index: 15, name: "大針蜂", evolution: "------", types: [.Insect, .Poison], movement: [Movement(level: 10, name: "雙針"), Movement(level: 11, name: "亂擊"), Movement(level: 14, name: "憤怒"), Movement(level: 17, name: "追打"), Movement(level: 20, name: "聚氣"), Movement(level: 23, name: "毒液衝擊"), Movement(level: 26, name: "惡意追擊"), Movement(level: 29, name: "毒菱"), Movement(level: 32, name: "飛彈針"), Movement(level: 35, name: "毒擊"), Movement(level: 38, name: "高速移動"), Movement(level: 41, name: "蠻幹"), Movement(level: 41, name: "致命針刺")]),
    Pokemon(index: 16, name: "波波", evolution: "LV18時進化成比比鳥", types: [.Normal, .Fly], movement: [Movement(level: 1, name: "撞擊"), Movement(level: 5, name: "潑沙"), Movement(level: 9, name: "起風"), Movement(level: 13, name: "電光一閃"), Movement(level: 17, name: "吹飛")]),
    Pokemon(index: 17, name: "比比鳥", evolution: "LV36時進化成比雕", types: [.Normal, .Fly], movement: [Movement(level: 22, name: "龍捲風"), Movement(level: 27, name: "羽毛舞"), Movement(level: 32, name: "高速移動")]),
    Pokemon(index: 18, name: "比雕", evolution: "-----", types: [.Normal, .Fly], movement: [ Movement(level: 38, name: "翅膀攻擊"), Movement(level: 44, name: "羽棲"), Movement(level: 50, name: "順風"), Movement(level: 56, name: "鸚鵡學舌"), Movement(level: 62, name: "空氣斬"), Movement(level: 68, name: "暴風")]),
    Pokemon(index: 19, name: "小拉達", evolution: "LV20時進化成拉達", types: [.Normal], movement: [Movement(level: 1, name: "撞擊"), Movement(level: 1, name: "搖尾巴"), Movement(level: 4, name: "電光一閃"), Movement(level: 7, name: "聚氣"),  Movement(level: 10, name: "咬住"), Movement(level: 13, name: "追打"), Movement(level: 16, name: "必殺門牙"), Movement(level: 19, name: "惡意追擊")]),
    Pokemon(index: 20, name: "拉達", evolution: "-----", types: [.Normal], movement: [Movement(level: 24, name: "咬碎"), Movement(level: 29, name: "突襲"), Movement(level: 34, name: "憤怒門牙"), Movement(level: 39, name: "捨身衝撞"),  Movement(level: 44, name: "蠻幹")]),
    Pokemon(index: 21, name: "烈雀", evolution: "LV20時進化成大嘴雀", types: [.Normal, .Fly], movement: [Movement(level: 1, name: "啄"), Movement(level: 1, name: "叫聲"), Movement(level: 4, name: "瞪眼"), Movement(level: 8, name: "追打"), Movement(level: 11, name: "亂擊"), Movement(level: 15, name: "燕返"), Movement(level: 18, name: "鸚鵡學舌")]),
    Pokemon(index: 22, name: "大嘴雀", evolution: "-----", types: [.Normal, .Fly], movement: [Movement(level: 23, name: "惡意追擊"), Movement(level: 27, name: "高速移動"), Movement(level: 32, name: "聚氣"), Movement(level: 36, name: "羽棲"), Movement(level: 41, name: "啄鑽"), Movement(level: 45, name: "直衝鑽")]),
    Pokemon(index: 23, name: "阿柏蛇", evolution: "LV22時進化成阿柏怪", types: [.Poison], movement: [Movement(level: 1, name: "緊束"), Movement(level: 1, name: "瞪眼"), Movement(level: 4, name: "毒針"), Movement(level: 9, name: "咬住"), Movement(level: 12, name: "大蛇瞪眼"), Movement(level: 17, name: "刺耳聲"), Movement(level: 20, name: "溶解液")]),
    Pokemon(index: 24, name: "阿柏怪", evolution: "-----", types: [.Poison], movement: [Movement(level: 27, name: "蓄力"), Movement(level: 27, name: "吞下"), Movement(level: 27, name: "噴出"), Movement(level: 32, name: "酸液炸彈"), Movement(level: 39, name: "泥巴炸彈"), Movement(level: 44, name: "胃液"), Movement(level: 48, name: "打嗝"), Movement(level: 51, name: "黑霧"), Movement(level: 56, name: "盤蜷"), Movement(level: 63, name: "垃圾射擊")]),
    Pokemon(index: 25, name: "皮卡丘", evolution: "使用雷之石進化成雷丘", types: [.Thunder], movement: [Movement(level: 1, name: "搖尾巴"), Movement(level: 1, name: "電擊"), Movement(level: 5, name: "叫聲"), Movement(level: 7, name: "和睦相處"), Movement(level: 10, name: "電光一閃"), Movement(level: 13, name: "電球"), Movement(level: 18, name: "電磁波"), Movement(level: 21, name: "仰攻"), Movement(level: 23, name: "影子分身"), Movement(level: 26, name: "電光"), Movement(level: 29, name: "蹭蹭臉頰"), Movement(level: 34, name: "放電"), Movement(level: 37, name: "摔打"), Movement(level: 42, name: "十萬伏特"), Movement(level: 45, name: "高速移動"), Movement(level: 50, name: "瘋狂伏特"), Movement(level: 53, name: "光牆"), Movement(level: 58, name: "打雷")]),
    Pokemon(index: 26, name: "雷丘", evolution: "-----", types: [.Thunder], movement: [Movement(level: 1, name: "搖尾巴"), Movement(level: 1, name: "電擊"), Movement(level: 5, name: "叫聲"), Movement(level: 7, name: "和睦相處"), Movement(level: 10, name: "電光一閃"), Movement(level: 13, name: "電球"), Movement(level: 18, name: "電磁波"), Movement(level: 21, name: "仰攻"), Movement(level: 23, name: "影子分身"), Movement(level: 26, name: "電光"), Movement(level: 29, name: "蹭蹭臉頰"), Movement(level: 34, name: "放電"), Movement(level: 37, name: "摔打"), Movement(level: 42, name: "十萬伏特"), Movement(level: 45, name: "高速移動"), Movement(level: 50, name: "瘋狂伏特"), Movement(level: 53, name: "光牆"), Movement(level: 58, name: "打雷")]),
    Pokemon(index: 27, name: "穿山鼠", evolution: "LV22時進化成穿山王", types: [.Ground], movement: [Movement(level: 1, name: "抓"), Movement(level: 1, name: "變圓"), Movement(level: 3, name: "潑沙"), Movement(level: 5, name: "毒針"), Movement(level: 7, name: "滾動"), Movement(level: 9, name: "高速旋轉"), Movement(level: 11, name: "連斬"), Movement(level: 14, name: "震級"), Movement(level: 17, name: "高速星星"), Movement(level: 20, name: "亂抓")]),
    Pokemon(index: 28, name: "穿山王", evolution: "-----", types: [.Ground], movement: [Movement(level: 24, name: "流沙地獄"), Movement(level: 28, name: "劈開"), Movement(level: 33, name: "挖洞"), Movement(level: 38, name: "陀螺球"), Movement(level: 43, name: "劍舞"), Movement(level: 48, name: "沙暴"), Movement(level: 53, name: "地震")]),
    Pokemon(index: 29, name: "尼多蘭", evolution: "LV16時進化成尼多娜", types: [.Poison], movement: [Movement(level: 1, name: "叫聲"), Movement(level: 1, name: "抓"), Movement(level: 7, name: "搖尾巴"), Movement(level: 9, name: "二連踢"), Movement(level: 13, name: "毒針")]),
    Pokemon(index: 30, name: "尼多娜", evolution: "使用月之石進化成尼多后", types: [.Poison], movement: [Movement(level: 20, name: "亂抓"), Movement(level: 23, name: "咬住"), Movement(level: 28, name: "幫助"), Movement(level: 35, name: "毒菱"), Movement(level: 38, name: "吹捧"), Movement(level: 43, name: "咬碎"), Movement(level: 50, name: "誘惑"), Movement(level: 58, name: "劇毒牙")]),
    Pokemon(index: 31, name: "尼多后", evolution: "-----", types: [.Poison, .Ground], movement: [Movement(level: 23, name: "逐步擊破"), Movement(level: 35, name: "泰山壓頂"), Movement(level: 43, name: "大地之力"), Movement(level: 58, name: "蠻力")]),
    Pokemon(index: 32, name: "尼多朗", evolution: "LV16時進化成尼多力諾", types: [.Poison], movement: [Movement(level: 1, name: "瞪眼"), Movement(level: 1, name: "啄"), Movement(level: 7, name: "聚氣"), Movement(level: 9, name: "二連踢"), Movement(level: 13, name: "毒針")]),
    Pokemon(index: 33, name: "尼多力諾", evolution: "使用月之石進化成尼多王", types: [.Poison], movement: [Movement(level: 20, name: "亂擊"), Movement(level: 23, name: "角撞"), Movement(level: 28, name: "幫助"), Movement(level: 35, name: "毒菱"), Movement(level: 38, name: "吹捧"),Movement(level: 43, name: "毒擊"), Movement(level: 50, name: "誘惑"), Movement(level: 58, name: "角鑽")]),
    Pokemon(index: 34, name: "尼多王", evolution: "-----", types: [.Poison, .Ground], movement: [Movement(level: 23, name: "逐步擊破"), Movement(level: 35, name: "大鬧一翻"), Movement(level: 43, name: "大地之力"), Movement(level: 58, name: "超級角擊")]),
    Pokemon(index: 35, name: "皮皮", evolution: "使用月之石進化成皮可西", types: [.Fairy], movement: [Movement(level: 1, name: "聚光燈"), Movement(level: 1, name: "魅惑之聲"), Movement(level: 1, name: "拍擊"), Movement(level: 1, name: "叫聲"),Movement(level: 1, name: "再來一次"), Movement(level: 7, name: "唱歌"), Movement(level: 10, name: "連環巴掌"), Movement(level: 13, name: "變圓"),Movement(level: 16, name: "看我嘛"), Movement(level: 19, name: "傳遞禮物"), Movement(level: 22, name: "喚醒巴掌")]),
    Pokemon(index: 36, name: "皮可西", evolution: "-----", types: [.Fairy], movement: [Movement(level: 25, name: "變小"),Movement(level: 28, name: "輔助力量"), Movement(level: 31, name: "指揮"), Movement(level: 34, name: "宇宙力量"), Movement(level: 37, name: "幸運咒語"),Movement(level: 40, name: "泰山壓頂"), Movement(level: 43, name: "月光"), Movement(level: 46, name: "月亮之力"), Movement(level: 49, name: "重力"),Movement(level: 50, name: "彗星拳"), Movement(level: 55, name: "治癒之願"), Movement(level: 58, name: "您先請")]),
    Pokemon(index: 37, name: "六尾", evolution: "使用火之石進化成九尾", types: [.Fire], movement: [Movement(level: 1, name: "火花"), Movement(level: 4, name: "搖尾巴"), Movement(level: 7, name: "吼叫"), Movement(level: 9, name: "圓瞳"),Movement(level: 10, name: "電光一閃"), Movement(level: 12, name: "奇異之光"), Movement(level: 15, name: "火焰漩渦"), Movement(level: 18, name: "以牙還牙"),Movement(level: 20, name: "鬼火"), Movement(level: 23, name: "出奇一擊")]),
    Pokemon(index: 38, name: "九尾", evolution: "-----", types: [.Fire], movement: [Movement(level: 26, name: "禍不單行"), Movement(level: 28, name: "烈焰濺射"), Movement(level: 31, name: "神通力"), Movement(level: 34, name: "神秘守護"),Movement(level: 36, name: "噴射火焰"), Movement(level: 39, name: "封印"), Movement(level: 42, name: "大字爆炎"), Movement(level: 44, name: "怨念"),Movement(level: 47, name: "誘惑"), Movement(level: 50, name: "煉獄")]),
    Pokemon(index: 39, name: "胖丁", evolution: "使用月之石進化成胖可丁", types: [.Normal, .Fairy], movement: [Movement(level: 1, name: "唱歌"), Movement(level: 3, name: "變圓"), Movement(level: 5, name: "拍擊"), Movement(level: 9, name: "和睦相處"),Movement(level: 11, name: "魅惑之聲"), Movement(level: 14, name: "定身法"), Movement(level: 17, name: "連環巴掌"), Movement(level: 20, name: "滾動"),Movement(level: 22, name: "輪唱")]),
    Pokemon(index: 40, name: "胖可丁", evolution: "-----", types: [.Normal, .Fairy], movement: [Movement(level: 25, name: "吞下"), Movement(level: 25, name: "噴出"), Movement(level: 25, name: "蓄力"), Movement(level: 27, name: "喚醒巴掌"),Movement(level: 30, name: "睡覺"), Movement(level: 32, name: "泰山壓頂"), Movement(level: 35, name: "陀螺球"), Movement(level: 38, name: "模仿"),Movement(level: 41, name: "巨聲"),Movement(level: 45, name: "捨身衝撞")])
    ]
//var po = Pokemon(index: 40, name: "胖可丁", evolution: "-----", types: [.Normal, .Fairy], movement: [Movement(level: 25, name: "吞下"), Movement(level: 25, name: "噴出"), Movement(level: 25, name: "蓄力"), Movement(level: 27, name: "喚醒巴掌"),Movement(level: 30, name: "睡覺"), Movement(level: 32, name: "泰山壓頂"), Movement(level: 35, name: "陀螺球"), Movement(level: 38, name: "模仿"),Movement(level: 41, name: "巨聲"),Movement(level: 45, name: "捨身衝撞")])

